name: Bug report
description: Report a problem or regression
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Clear and concise description
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: cxusage version
      placeholder: e.g. 0.1.0
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g. 3.11.9
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide commands/config/log snippets to reproduce
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant output/logs
      render: shell

